### ISSUE TITLE
provide an online demo

### ISSUE THREAD

**Issue by CavalcanteLeo** [jeremyhamm/vue-slider#8]
provide an online demo, then i can download or not if works as i expect. Not only a poor gif

**Comment by jeremyhamm** [comment]
If you would like a demo please create and commit one.  That would be appreciated!

**Comment by CavalcanteLeo** [comment]
i haven't tested it because it has no online demo. I don't use anything that i can't test.
Many other may do the same, just a tip, face as you like

**Comment by jeremyhamm** [comment]
`git clone https://github.com/jeremyhamm/vue-slider` There's your demo

**Comment by CavalcanteLeo** [comment]
as I said, i won't clone anything before I can test

**Comment by jeremyhamm** [comment]
Well then you are going to have to find a different library.  No time to develop a demo I am not getting paid for.
