### ISSUE TITLE
Customize menu icon

### ISSUE THREAD

**Issue by ianaz** [jeremyhamm/vue-slider#9]
Thanks for sharing!
Would be nice to be able to customize the menu icon and styles in a better way, maybe via props...?

For now I'm overriding the styles in css with !important as is the only way it works for me:

```
<style lang="scss">
  .navMenu {
    background-color: black !important;
  }
...
```

**Comment by jeremyhamm** [comment]
That's a great idea!  Would you mind opening an issue for that?
